import { AlertTriangle, Armchair, BadgeDollarSign, BellRing, Boxes, Building, Building2, ClipboardCheck, FileBarChart, KeyRound, Megaphone, MessageSquare, Shield, Siren, Users, Wrench } from "lucide-react";

export type ModuleRoute = {
  slug: string;
  label: string;
  endpoint?: string;
  permission: string;
  description: string;
  icon: typeof Building;
  columns: string[];
};

export const MODULE_ROUTES: ModuleRoute[] = [
  { slug: "societies", label: "Societies", endpoint: "/societies", permission: "societies", description: "Society-level hierarchy and portfolio controls.", icon: Building2, columns: ["society_name", "city", "total_blocks", "total_units", "occupied_units", "occupancy_percentage"] },
  { slug: "blocks", label: "Blocks", endpoint: "/blocks", permission: "blocks", description: "Buildings and towers under the selected society.", icon: Building, columns: ["block_name", "total_floors", "is_active", "created_at"] },
  { slug: "units", label: "Units", endpoint: "/units", permission: "units", description: "Apartments, flats, villas, rooms, and dwelling records.", icon: Boxes, columns: ["unit_number", "unit_type", "block_name", "occupancy_status"] },
  { slug: "residents", label: "Residents", endpoint: "/residents", permission: "residents", description: "Resident profiles, vehicles, documents, and history.", icon: Users, columns: ["full_name", "mobile_primary", "resident_type", "unit_number", "block_name"] },
  { slug: "visitors", label: "Visitors", endpoint: "/visitors", permission: "visitors", description: "Visitor entries, invites, gate operations, deliveries, and SOS.", icon: Siren, columns: ["visitor_name", "visitor_mobile", "visitor_type", "status", "created_at"] },
  { slug: "complaints", label: "Complaints", endpoint: "/complaints", permission: "complaints", description: "Complaint lifecycle, assignment, media, status, and ratings.", icon: MessageSquare, columns: ["title", "category_name", "status", "priority", "created_at"] },
  { slug: "maintenance", label: "Maintenance", endpoint: "/maintenance-heads", permission: "maintenance", description: "Maintenance heads, schedules, collections, and operations.", icon: Wrench, columns: ["name", "amount", "frequency", "is_active"] },
  { slug: "finance", label: "Finance", endpoint: "/invoices", permission: "finance", description: "Invoices, payments, expenses, approvals, and finance dashboard.", icon: BadgeDollarSign, columns: ["invoice_number", "resident_name", "status", "total_amount", "due_date"] },
  { slug: "amenities", label: "Amenities", endpoint: "/amenities", permission: "amenities", description: "Amenity inventory, bookings, capacity, and availability.", icon: Armchair, columns: ["name", "description", "is_active", "created_at"] },
  { slug: "staff", label: "Staff & Vendors", endpoint: "/staff", permission: "staff", description: "Staff, vendors, shifts, assignments, and service categories.", icon: ClipboardCheck, columns: ["name", "role", "mobile", "is_active"] },
  { slug: "assets", label: "Assets & Inventory", endpoint: "/assets", permission: "assets", description: "Asset registry, maintenance state, ownership, and location.", icon: Boxes, columns: ["asset_name", "asset_type", "status", "next_service_date"] },
  { slug: "communication", label: "Communication", endpoint: "/notices", permission: "communication", description: "Broadcasts, campaigns, templates, and delivery tracking.", icon: Megaphone, columns: ["title", "channel", "status", "created_at"] },
  { slug: "notices", label: "Notices", endpoint: "/notices", permission: "notices", description: "Official notices and resident announcements.", icon: BellRing, columns: ["title", "notice_type", "published_at", "status"] },
  { slug: "meetings", label: "Meetings", endpoint: "/meetings", permission: "meetings", description: "Committee meetings, agenda, minutes, and attendance.", icon: ClipboardCheck, columns: ["title", "meeting_date", "status", "venue"] },
  { slug: "compliance", label: "Compliance", endpoint: "/compliance", permission: "compliance", description: "Documents, renewals, approvals, and statutory tracking.", icon: Shield, columns: ["title", "category", "status", "expiry_date"] },
  { slug: "reports", label: "Reports", endpoint: "/dashboard/metrics", permission: "reports", description: "Society-wise, block-wise, unit-wise, and date-range reports.", icon: FileBarChart, columns: ["report_name", "scope", "updated_at", "status"] },
  { slug: "roles", label: "Roles & Permissions", endpoint: "/users", permission: "roles", description: "Dynamic roles, cloned permissions, and access visibility.", icon: KeyRound, columns: ["full_name", "role", "email", "is_active"] },
  { slug: "users", label: "Users", endpoint: "/users", permission: "users", description: "Users, role assignment, invitations, activity, and status.", icon: Users, columns: ["full_name", "email", "role", "is_active"] }
];

export const EXTRA_MODULE_ROUTES: ModuleRoute[] = [
  { slug: "residents/overview", label: "Resident Overview", endpoint: "/residents", permission: "residents", description: "Resident occupancy stats, move-in/out trends, and quick actions.", icon: Users, columns: ["full_name", "resident_type", "unit_number", "block_name", "is_active"] },
  { slug: "residents/leases", label: "Lease Agreements", endpoint: "/residents", permission: "residents", description: "Lease, rental, and occupancy records connected to resident and unit data.", icon: Users, columns: ["full_name", "resident_type", "unit_number", "block_name", "is_active"] },
  { slug: "residents/vehicles", label: "Vehicle Management", endpoint: "/residents", permission: "residents", description: "Resident-linked vehicle overview for access and parking operations.", icon: Users, columns: ["full_name", "mobile_primary", "unit_number", "block_name", "is_active"] },
  { slug: "residents/pets", label: "Pet Management", endpoint: "/residents", permission: "residents", description: "Resident pet registry workspace backed by the resident directory.", icon: Users, columns: ["full_name", "resident_type", "unit_number", "block_name", "is_active"] },
  { slug: "residents/move", label: "Move In / Move Out", endpoint: "/residents", permission: "residents", description: "Move-in and move-out management for resident transitions.", icon: Users, columns: ["full_name", "unit_number", "block_name", "is_active"] },
  { slug: "residents/qr-pass", label: "Resident QR Pass", endpoint: "/residents", permission: "residents", description: "Generate and download QR passes for resident identity and access.", icon: Users, columns: ["full_name", "unit_number", "block_name", "is_active"] },
  { slug: "residents/import", label: "Bulk Import", endpoint: "/residents", permission: "residents", description: "Bulk import residents via CSV template upload.", icon: Users, columns: ["full_name", "resident_type", "unit_number", "block_name"] },
  { slug: "visitors/logs", label: "Visitor Logs", endpoint: "/visitors", permission: "visitors", description: "Complete visitor entry and exit log with filter and search.", icon: Siren, columns: ["visitor_name", "visitor_mobile", "visitor_type", "status", "created_at"] },
  { slug: "visitors/security", label: "Security Dashboard", endpoint: "/visitors", permission: "visitors", description: "Live gate traffic, active visitor, and security desk monitoring.", icon: Siren, columns: ["visitor_name", "visitor_mobile", "visitor_type", "status", "created_at"] },
  { slug: "visitors/checkin", label: "Visitor Check-In", endpoint: "/visitors", permission: "visitors", description: "Visitor check-in queue with current entry status and contact details.", icon: Siren, columns: ["visitor_name", "visitor_mobile", "visitor_type", "status", "created_at"] },
  { slug: "visitors/guard", label: "Guard Panel", endpoint: "/visitors", permission: "visitors", description: "Guard-facing queue for visitor approval, entry, and exit actions.", icon: Shield, columns: ["visitor_name", "visitor_mobile", "visitor_type", "status", "created_at"] },
  { slug: "visitors/qr", label: "QR Entry", endpoint: "/visitor-passes", permission: "visitors", description: "Recurring visitor passes and QR entry records.", icon: Siren, columns: ["visitor_name", "unit_id", "is_active", "valid_from", "valid_to"] },
  { slug: "visitors/deliveries", label: "Delivery Tracking", endpoint: "/delivery-entries", permission: "visitors", description: "Courier and delivery entries moving through the gate workflow.", icon: Siren, columns: ["delivery_type", "delivery_person_name", "status", "created_at"] },
  { slug: "visitors/attendance", label: "Staff Attendance", endpoint: "/staff", permission: "visitors", description: "Staff and vendor presence view for security operations.", icon: ClipboardCheck, columns: ["name", "role", "mobile", "is_active"] },
  { slug: "visitors/sos", label: "SOS / Emergency", endpoint: "/sos-alerts", permission: "visitors", description: "Emergency alerts, escalation state, and resolution tracking.", icon: Siren, columns: ["alert_type", "status", "unit_id", "created_at"] },
  { slug: "visitors/passes", label: "Guest Passes", endpoint: "/visitor-passes", permission: "visitors", description: "Guest pass lifecycle, validity, and activation state.", icon: Siren, columns: ["visitor_name", "unit_id", "is_active", "valid_from", "valid_to"] },
  { slug: "complaints/dashboard", label: "Complaints Dashboard", endpoint: "/complaints", permission: "complaints", description: "Complaint analytics, SLA state, priority queues, and resolution trends.", icon: MessageSquare, columns: ["title", "category_name", "status", "priority", "created_at"] },
  { slug: "complaints/new", label: "Raise Complaint", endpoint: "/complaints", permission: "complaints", description: "Complaint intake workspace using the live complaint registry.", icon: MessageSquare, columns: ["title", "category_name", "status", "priority", "created_at"] },
  { slug: "complaints/sla", label: "SLA Monitoring", endpoint: "/complaints", permission: "complaints", description: "Open and in-progress complaints monitored for SLA risk.", icon: MessageSquare, columns: ["title", "category_name", "status", "priority", "created_at"] },
  { slug: "complaints/escalation", label: "Escalation Queue", endpoint: "/complaints", permission: "complaints", description: "Critical and high-priority complaint escalation queue.", icon: MessageSquare, columns: ["title", "category_name", "status", "priority", "created_at"] },
  { slug: "complaints/maintenance", label: "Maintenance Requests", endpoint: "/complaints", permission: "complaints", description: "Maintenance-related complaint requests and service follow-up.", icon: Wrench, columns: ["title", "category_name", "status", "priority", "created_at"] },
  { slug: "complaints/analytics", label: "Complaint Analytics", endpoint: "/complaints", permission: "complaints", description: "Trend analysis, resolution times, SLA compliance, and category breakdowns.", icon: MessageSquare, columns: ["title", "category_name", "status", "priority", "created_at"] },
  { slug: "financials", label: "Finance Dashboard", endpoint: "/invoices", permission: "finance", description: "Invoice, collection, overdue, and finance analytics from live invoices.", icon: BadgeDollarSign, columns: ["invoice_number", "resident_name", "status", "total_amount", "due_date"] },
  { slug: "financials/invoices", label: "Invoices", endpoint: "/invoices", permission: "finance", description: "Invoice register with payment status and due dates.", icon: BadgeDollarSign, columns: ["invoice_number", "resident_name", "status", "total_amount", "due_date"] },
  { slug: "financials/payments", label: "Payments", endpoint: "/invoices", permission: "finance", description: "Payment collection view aggregated from invoice paid amounts.", icon: BadgeDollarSign, columns: ["invoice_number", "resident_name", "paid_amount", "status", "due_date"] },
  { slug: "financials/expenses", label: "Expense Tracking", endpoint: "/expenses", permission: "finance", description: "Society expenses, GST amounts, approvals, and vendor spend.", icon: BadgeDollarSign, columns: ["description", "amount", "gst_amount", "status", "expense_date"] },
  { slug: "financials/gst", label: "GST Reports", endpoint: "/expenses", permission: "finance", description: "GST reporting workspace backed by expense GST data.", icon: FileBarChart, columns: ["description", "amount", "gst_amount", "status", "expense_date"] },
  { slug: "financials/penalties", label: "Penalty Management", endpoint: "/invoices", permission: "finance", description: "Penalty and overdue invoice monitoring for finance teams.", icon: BadgeDollarSign, columns: ["invoice_number", "resident_name", "balance_due", "status", "due_date"] },
  { slug: "financials/reports", label: "Financial Reports", endpoint: "/invoices", permission: "finance", description: "Finance report view for invoice, collection, and overdue summaries.", icon: FileBarChart, columns: ["invoice_number", "resident_name", "total_amount", "status", "due_date"] },
  { slug: "visitors/patrol",         label: "Patrol Dashboard",   endpoint: "/patrol/dashboard",   permission: "visitors", description: "Real-time patrol session monitoring and completion stats.",              icon: Shield,        columns: ["guard_id", "patrol_status", "scanned_points", "total_points", "completion_pct"] },
  { slug: "visitors/patrol/qr",      label: "Patrol QR Points",   endpoint: "/patrol/qr-points",   permission: "visitors", description: "Create and manage patrol QR checkpoint points.",                       icon: Shield,        columns: ["label", "block_name", "floor_number", "is_active"] },
  { slug: "visitors/patrol/history", label: "Patrol History",     endpoint: "/patrol/history",     permission: "visitors", description: "Historical patrol session records and completion data.",               icon: Shield,        columns: ["guard_id", "patrol_status", "scanned_points", "started_at"] },
  { slug: "visitors/patrol/fraud",   label: "Patrol Fraud Flags", endpoint: "/patrol/fraud-flags", permission: "visitors", description: "Detected fraud and geo-spoofing flags from patrol sessions.",          icon: AlertTriangle, columns: ["guard_id", "flag_type", "flagged_at", "is_reviewed"] }
];
